### PR TITLE
Ensure files starting on a new piece aren't marked complete twice

### PR DESCRIPTION
**Pull request by kannibalox**
Fixes https://github.com/rakshasa/rtorrent/issues/1248

### CODE REVIEW

**Comment by stickz** [comment]
This pull request has a regression where the completion file list is reported as less than 100% when completed.

**Comment by kannibalox** [comment]
Is there any further information you can provide? The size and order of the files in question and the piece size would be great. I tried a bunch of things, including setting some of the files to "off" priority, but was unable to reproduce.

**Comment by kannibalox** [comment]
That should cover all cases, including zero-length files, but I'll do further testing and maybe even take a stab at unit tests to prove it out.

**Comment by stickz** [comment]
Thanks. I'm working on pushing some of these fixes to various vendors. I backported changes from jesec as well.

**Comment by stickz** [comment]
This pull request is still broken. Here's an example where the file completion percentage reports incorrectly.
https://github.com/swizzin/swizzin/issues/1106

Running the same code with a patch. 
https://github.com/swizzin/swizzin/blob/master/sources/patches/rtorrent/piece-boundary-fix-0.13.8.patch

**Comment by kannibalox** [comment]
Very strange, I made sure to test what this condition at least looks to be and it functions correctly, I'll have to find a way to reproduce it.

**Comment by kannibalox** [comment]
Closing for now, as this approach to the fix still has some weird edge cases that need working out.

**Pull request closed without merging**
